- hosts: all
  become: true
  tasks:
    - name: Bootstrap Python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
    - name: Clone Voting App Repository
      git:
        repo: https://github.com/csubirana/voting-app.git
        dest: /opt/voting-app

    - name: Install Dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python-pip
        - docker.io
        - docker-compose
        # Add other dependencies as needed

    - name: Install Python Dependencies
      pip:
        requirements: /opt/voting-app/requirements.txt
      become_user: your-app-user

    - name: Build and Start Docker Containers
      command: docker-compose up -d
      args:
        chdir: /opt/voting-app
