name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code
        run: flake8 voting-app/azure-vote/main.py

      - name: Security check
        run: bandit -r voting-app/azure-vote/main.py

  build_and_push_docker:
    needs: lint_and_security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build -t csubirana/voting-app:v1 .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push csubirana/voting-app:v1
