name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Security Scan
        pip : pip install bandit
        run: bandit -r src/

  build-packer:
    runs-on: ubuntu-latest
    needs: [lint-python, security-scan]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: Build Packer Image
        run: packer build -var-file=variables.json packer-template.json

  push-docker-hub:
    runs-on: ubuntu-latest
    needs: build-packer
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag your-image:latest ${{ secrets.DOCKER_USERNAME }}/your-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image:latest
